//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wreq {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("wreq.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add irrigation.
        /// </summary>
        public static string AddIrrigation {
            get {
                return ResourceManager.GetString("AddIrrigation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new.
        /// </summary>
        public static string AddNew {
            get {
                return ResourceManager.GetString("AddNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add water limitation.
        /// </summary>
        public static string AddWaterLimit {
            get {
                return ResourceManager.GetString("AddWaterLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alt. above sea level.
        /// </summary>
        public static string Altitude {
            get {
                return ResourceManager.GetString("Altitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wreq.
        /// </summary>
        public static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area.
        /// </summary>
        public static string Area {
            get {
                return ResourceManager.GetString("Area", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kleyms Alexey.
        /// </summary>
        public static string Author {
            get {
                return ResourceManager.GetString("Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change your account settings.
        /// </summary>
        public static string ChangeAccountSettings {
            get {
                return ResourceManager.GetString("ChangeAccountSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change password.
        /// </summary>
        public static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comb. cult. height.
        /// </summary>
        public static string CombCulture {
            get {
                return ResourceManager.GetString("CombCulture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm new password.
        /// </summary>
        public static string ConfirmNewPassword {
            get {
                return ResourceManager.GetString("ConfirmNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password.
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password and confirmation password do not match..
        /// </summary>
        public static string ConfirmPasswordValidationError {
            get {
                return ResourceManager.GetString("ConfirmPasswordValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crop.
        /// </summary>
        public static string Crop {
            get {
                return ResourceManager.GetString("Crop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Water requirement.
        /// </summary>
        public static string CropPlan {
            get {
                return ResourceManager.GetString("CropPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crops.
        /// </summary>
        public static string Crops {
            get {
                return ResourceManager.GetString("Crops", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Culture.
        /// </summary>
        public static string CultureC {
            get {
                return ResourceManager.GetString("CultureC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cultures.
        /// </summary>
        public static string Cultures {
            get {
                return ResourceManager.GetString("Cultures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current password.
        /// </summary>
        public static string CurrentPassword {
            get {
                return ResourceManager.GetString("CurrentPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Begin date.
        /// </summary>
        public static string DateBegin {
            get {
                return ResourceManager.GetString("DateBegin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End date.
        /// </summary>
        public static string DateEnd {
            get {
                return ResourceManager.GetString("DateEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End date should be greater than begin date.
        /// </summary>
        public static string DateEndValidationError {
            get {
                return ResourceManager.GetString("DateEndValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of sowing.
        /// </summary>
        public static string DateSeeded {
            get {
                return ResourceManager.GetString("DateSeeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this?.
        /// </summary>
        public static string DeleteConfirm {
            get {
                return ResourceManager.GetString("DeleteConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while processing your request..
        /// </summary>
        public static string ErrorMessage {
            get {
                return ResourceManager.GetString("ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error..
        /// </summary>
        public static string ErrorMessageHeader {
            get {
                return ResourceManager.GetString("ErrorMessageHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field.
        /// </summary>
        public static string Field {
            get {
                return ResourceManager.GetString("Field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fields.
        /// </summary>
        public static string Fields {
            get {
                return ResourceManager.GetString("Fields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field water capacity.
        /// </summary>
        public static string FWC {
            get {
                return ResourceManager.GetString("FWC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field water capacity must be greater than wilt water capacity.
        /// </summary>
        public static string FWCValidationError {
            get {
                return ResourceManager.GetString("FWCValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get plans.
        /// </summary>
        public static string GetPlans {
            get {
                return ResourceManager.GetString("GetPlans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wreq.
        /// </summary>
        public static string HomePage {
            get {
                return ResourceManager.GetString("HomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index.
        /// </summary>
        public static string Index {
            get {
                return ResourceManager.GetString("Index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Irrigation.
        /// </summary>
        public static string Irrigation {
            get {
                return ResourceManager.GetString("Irrigation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Irrigations.
        /// </summary>
        public static string Irrigations {
            get {
                return ResourceManager.GetString("Irrigations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Irrigation type.
        /// </summary>
        public static string IrrigationType {
            get {
                return ResourceManager.GetString("IrrigationType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Irrigation types.
        /// </summary>
        public static string IrrigationTypes {
            get {
                return ResourceManager.GetString("IrrigationTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There may be only one irrigation record for one day.
        /// </summary>
        public static string IrrigationValidationError {
            get {
                return ResourceManager.GetString("IrrigationValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kc end.
        /// </summary>
        public static string KcEnd {
            get {
                return ResourceManager.GetString("KcEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kc ini.
        /// </summary>
        public static string KcIni {
            get {
                return ResourceManager.GetString("KcIni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kc mid.
        /// </summary>
        public static string KcMid {
            get {
                return ResourceManager.GetString("KcMid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ky.
        /// </summary>
        public static string Ky {
            get {
                return ResourceManager.GetString("Ky", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latitude.
        /// </summary>
        public static string Latitude {
            get {
                return ResourceManager.GetString("Latitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lattitude must be between -90 and 90.
        /// </summary>
        public static string LattitudeValidationError {
            get {
                return ResourceManager.GetString("LattitudeValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dev. stage length.
        /// </summary>
        public static string Ldev {
            get {
                return ResourceManager.GetString("Ldev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End. stage length.
        /// </summary>
        public static string Lend {
            get {
                return ResourceManager.GetString("Lend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ini. stage length.
        /// </summary>
        public static string Lini {
            get {
                return ResourceManager.GetString("Lini", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mid. stage length.
        /// </summary>
        public static string Lmid {
            get {
                return ResourceManager.GetString("Lmid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This account has been locked out, please try again later..
        /// </summary>
        public static string LockedOutMessage {
            get {
                return ResourceManager.GetString("LockedOutMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locked out..
        /// </summary>
        public static string LockedOutMessageHeader {
            get {
                return ResourceManager.GetString("LockedOutMessageHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locked Out.
        /// </summary>
        public static string LockedOutTitle {
            get {
                return ResourceManager.GetString("LockedOutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string LogIn {
            get {
                return ResourceManager.GetString("LogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InvalidLoginAttempt.
        /// </summary>
        public static string LoginError {
            get {
                return ResourceManager.GetString("LoginError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log off.
        /// </summary>
        public static string LogOff {
            get {
                return ResourceManager.GetString("LogOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Longitude.
        /// </summary>
        public static string Longitude {
            get {
                return ResourceManager.GetString("Longitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Longitude must be between -180 and 180.
        /// </summary>
        public static string LongitudeValidationError {
            get {
                return ResourceManager.GetString("LongitudeValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage account.
        /// </summary>
        public static string ManageAccount {
            get {
                return ResourceManager.GetString("ManageAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max height.
        /// </summary>
        public static string MaxHeight {
            get {
                return ResourceManager.GetString("MaxHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max root depth.
        /// </summary>
        public static string MaxRoot {
            get {
                return ResourceManager.GetString("MaxRoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password.
        /// </summary>
        public static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} must be at least {2} characters long..
        /// </summary>
        public static string PasswordValidationError {
            get {
                return ResourceManager.GetString("PasswordValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plan irrigations.
        /// </summary>
        public static string PlanIrrigations {
            get {
                return ResourceManager.GetString("PlanIrrigations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Begin date cannot be less than the date of sowing.
        /// </summary>
        public static string PlanningDateBeginError {
            get {
                return ResourceManager.GetString("PlanningDateBeginError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nd date cannot be greater than total duration of plant growth stages.
        /// </summary>
        public static string PlanningDateEndTooBigError {
            get {
                return ResourceManager.GetString("PlanningDateEndTooBigError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value must be a positive number between 0 and 1.
        /// </summary>
        public static string Positive01ValidationError {
            get {
                return ResourceManager.GetString("Positive01ValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value must be a positive number.
        /// </summary>
        public static string PositiveValidationError {
            get {
                return ResourceManager.GetString("PositiveValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value ‘{0}’ is not valid for {1}.
        /// </summary>
        public static string PropertyValueInvalid {
            get {
                return ResourceManager.GetString("PropertyValueInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This record is being used.
        /// </summary>
        public static string RecordUsed {
            get {
                return ResourceManager.GetString("RecordUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember be?.
        /// </summary>
        public static string RememberMe {
            get {
                return ResourceManager.GetString("RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Readily evaporable water.
        /// </summary>
        public static string REW {
            get {
                return ResourceManager.GetString("REW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REW value must be greater than TEW value.
        /// </summary>
        public static string REWValidationError {
            get {
                return ResourceManager.GetString("REWValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soil type.
        /// </summary>
        public static string SoilType {
            get {
                return ResourceManager.GetString("SoilType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soil types.
        /// </summary>
        public static string SoilTypes {
            get {
                return ResourceManager.GetString("SoilTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total evaporable water.
        /// </summary>
        public static string TEW {
            get {
                return ResourceManager.GetString("TEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TEW value must be greater than REW value.
        /// </summary>
        public static string TEWValidationError {
            get {
                return ResourceManager.GetString("TEWValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        public static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to дней.
        /// </summary>
        public static string UnitDays {
            get {
                return ResourceManager.GetString("UnitDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to м.
        /// </summary>
        public static string UnitMeter {
            get {
                return ResourceManager.GetString("UnitMeter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to мм.
        /// </summary>
        public static string UnitMilimeter {
            get {
                return ResourceManager.GetString("UnitMilimeter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View irrigations.
        /// </summary>
        public static string ViewIrrigations {
            get {
                return ResourceManager.GetString("ViewIrrigations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View water limitation.
        /// </summary>
        public static string ViewWaterLimits {
            get {
                return ResourceManager.GetString("ViewWaterLimits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume.
        /// </summary>
        public static string Volume {
            get {
                return ResourceManager.GetString("Volume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Water extraction.
        /// </summary>
        public static string WaterExtr {
            get {
                return ResourceManager.GetString("WaterExtr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Water limit.
        /// </summary>
        public static string WaterLimit {
            get {
                return ResourceManager.GetString("WaterLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There may be no overlapping water limits.
        /// </summary>
        public static string WaterLimitsValidationError {
            get {
                return ResourceManager.GetString("WaterLimitsValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wetted soil area fraction.
        /// </summary>
        public static string WettedSoilAreaFraction {
            get {
                return ResourceManager.GetString("WettedSoilAreaFraction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wilt water capacity.
        /// </summary>
        public static string WWC {
            get {
                return ResourceManager.GetString("WWC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wilt water capacity must be less than field water capacity.
        /// </summary>
        public static string WWCValidationError {
            get {
                return ResourceManager.GetString("WWCValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yield reduction.
        /// </summary>
        public static string YieldReduction {
            get {
                return ResourceManager.GetString("YieldReduction", resourceCulture);
            }
        }
    }
}
